services:
  postservice-database:
    hostname: posts-database
    image: postgres:16
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5

  post-service:
    depends_on:
      shared:
        condition: service_started
      postservice-database:
        condition: service_healthy
    hostname: post-service
    build:
      context: ../
      dockerfile: post-service/Dockerfile
      args:
        - GRPC_PORT=9090
    environment:
      - GRPC_ADDR=0.0.0.0:9090
      - DATABASE_ADDR=postgresql://postgres@posts-database:5432/postgres
