services:
  api-service:
    depends_on:
      - shared
      - user-service
    hostname: api-service
    build:
      context: ../
      dockerfile: api-service/Dockerfile
    environment:
      - USERSERVICE_GRPC_ADDR=user-service:$USERSERVICE_GRPC_PORT
    ports:
      - 8080:8080

