FROM alpine:3.14 as build

# RUN apk add --no-cache make
# RUN apk add --no-cache protoc-gen-go

WORKDIR /app/shared

COPY shared /app/shared/

# ENTRYPOINT [ "make", "compile_proto" ]

ENTRYPOINT [ "true" ]
